version: '2'
services:

  web:
    env_file:
      - ../../../config/birthdays-calendar/secrets.env
    networks: 
      front_internal:
        aliases: 
          - birthdays-calendar.local

networks:
  front_internal:
    external: true
