version: '3.7'
services:

  web:
    volumes:
      - ../../../data/rlcs-calendar/logs:/app/logs
    networks: 
      front_internal:
        aliases: 
          - rlcs-calendar.local

networks:
  front_internal:
    external: true
