version: '3.7'
services:

  caddy:
    image: abiosoft/caddy:no-stats
    restart: always
    environment:
      ACME_AGREE: 'true'
    volumes:
      - ./www:/www
      - ./Caddyfile:/etc/Caddyfile:ro
      - ./data:/root/.caddy
      - ../../data/front/logs:/etc/logs
